# Generated by Django 4.0.1 on 2022-01-13 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_blogz_blog'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='blog1',
        ),
    ]
