# Generated by Django 4.0.1 on 2022-01-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_blog_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='writer',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
